FROM node:18-alpine

WORKDIR /app

# Копируем зависимости
COPY package*.json ./

# Используем npm install вместо npm ci
RUN npm install

# Копируем код
COPY . .

ENV NODE_OPTIONS=--experimental-vm-modules

CMD ["npm", "run", "test:ci"]
