name: Deploy to Server

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: self-hosted
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Deploy via SSH
        run: |
          ssh -o StrictHostKeyChecking=no -p ${{ secrets.SSH_PORT }} \
            -i /home/nekit/.ssh/id_rsa_github_new \
            ${{ secrets.SERVER_USER }}@${{ secrets.SERVER_HOST }} "
            cd /home/developer/app && \
            git pull origin main && \
            docker-compose down && \
            docker-compose up -d --build
          "